[main]
domain = 'yourdomain.com'
ns1 = '127.0.0.1'
ns2 = '127.0.0.1'

# server address
listen_addr = '0.0.0.0:53'

# debug (0 or 1)
debug = 0

# default TTL
ttl = 60

# default latency (in ms)
sleep = 0

# a 3rdparty domain which we don't own
a3rdparty_domain = 'whatever.com'

known_servers = """
127.0.0.1   localhost
1.2.3.4     powerdns1
1.2.3.5     powerdns2
2.3.4.5     bind-test1
4.5.6.7     msdns-test1
"""
