[module]
name = "cnchain"
type = "feature"
info = "CNAME Alias Chains"
short = "CNAME chain alias generator"
category = "Alias chains"
records = "CNAME"
tags = "Domain Lock-Up, Denial of Service"
rfc = "RFC1034"
desc = '''
This module implements **incremental alias chains** using **CNAME (Canonical Name)** records. It returns an alias record with an incremented domain name index, forming a chain that continues to increment indefinitely.

Specifically, this module generates a CNAME alias record in the format `cnchain###.yourdomain.com`, where `###` represents the incremented index.

The concept is that if the client/resolver attempts to resolve this alias further, it will generate yet another incremented alias, causing the process to continue indefinitely and potentially keeping the resolver occupied.

However, in practice, most modern resolvers detect such chains and terminate the resolution after encountering a certain number of consecutive aliases (e.g., 20 aliases) or upon reaching a specified time limit for the resolution (e.g., 30 seconds).

Note that this feature provides the same functionality as requesting a CNAME record for the generic [chain] feature.

:warning:**BEWARE**:warning:This could potentially lead to a **domain lock-up (DoS)**.
'''
format = '''
**`cnchain<NUMBER>.yourdomain.com`**

Where:

- The **`<NUMBER>`** parameter specifies an arbitrary number that will be incremented in the response.
'''
seealso = "cnalias, cnloop, chain, cnchain, dnchain, htchain, mxchain, nschain, spfchain, srchain, svchain"

[[module.example]]
description = "By default, the module generates a CNAME alias with the index of 1:"
command = "dig cnchain.yourdomain.com @127.0.0.1"

[[module.example]]
description = "If we attempt to resolve the resulting domain name (`cnchain1.yourdomain.com`), we receive an incremented alias record:"
command = "dig cnchain1.yourdomain.com @127.0.0.1"

[[module.example]]
description = "If we continue to resolve the next domain name (`cnchain2.yourdomain.com`), we again receive an incremented alias record:"
command = "dig cnchain2.yourdomain.com @127.0.0.1"

[[module.example]]
description = "This resolution process can continue indefinitely, as there are no limits on the size of the index number. Each resolution yields another incremented alias record:"
command = "dig cnchain9999999999999999999999999.yourdomain.com @127.0.0.1"
append = "The domain name will never be fully resolved as the incremental process continues indefinitely."

[module.code]
python = '''
if req.first_subdomain.startswith("cnchain"):
   # Send incremented CNAME alias
   new_domain_name = increment_chain()
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   ### ANSWER SECTION ########
   # CNAME
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
   buffer += getTypeBin("CNAME") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                    ## TTL
   buffer += struct.pack(">H", len(new_domain_name)+2)      ## Data length
   buffer += convDom2Bin(new_domain_name)                   ## CNAME value
   # log and send
   log("CNAME %s" % (new_domain_name))
   send_buf(self, buffer)
   #####################################################################
'''
